# Generated by Django 2.1.3 on 2018-12-06 04:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=10)),
                ('image', models.FileField(default='settings.MEDIA_ROOT/default.jpg', storage=django.core.files.storage.FileSystemStorage(location='G:\\Project-5\\web\\trafficlight\\media'), upload_to='media')),
            ],
            options={
                'db_table': 'Display',
            },
        ),
    ]
